services:
  influxdb-logger:
    build: .
    image: ghcr.io/pudap/influxdb-logger:latest
    container_name: influxdb-logger
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
